// Static IATA → { timezone, country, lat, lng } lookup.
//
// Flight times on boarding passes are always wall-clock time at the
// relevant airport. To display them honestly we need to know each
// airport's IANA timezone — without it, a stored UTC instant gets
// rendered in the server's timezone and an Asia trip's itinerary
// drifts by hours.
//
// We also keep the airport's ISO 3166-1 alpha-2 country code so
// callers (e.g. the segment form) can derive origin / destination
// country from a typed IATA without an extra round-trip.
//
// And we keep WGS84 lat/lng so the trip-detail map can pin flight
// destinations without a geocoding round-trip.
//
// Source data is `iata-airports.json` in this directory, generated by
// `scripts/fetch-airports.ts` from OpenFlights. Airports change rarely
// (and the IATA↔IANA-timezone / IATA↔country mappings more rarely
// still), so we ship a snapshot rather than calling an API at runtime
// — same pattern as `src/lib/airlines/` (CLAUDE.md guardrail #13 /
// ADR-0009).

import airportsData from './iata-airports.json';

interface AirportEntry {
  tz: string;
  /** ISO 3166-1 alpha-2 code. Optional: a small number of airports
   *  don't resolve to a single ISO country. */
  country?: string;
  /** WGS84 latitude. Optional: dropped from output when the upstream
   *  row had a malformed or out-of-range value. */
  lat?: number;
  /** WGS84 longitude. Optional under the same conditions as lat. */
  lng?: number;
}

const AIRPORTS: Readonly<Record<string, AirportEntry>> = airportsData as Record<
  string,
  AirportEntry
>;

// IATA airport codes are always 3 letters.
const IATA_AIRPORT = /^[A-Z]{3}$/;

function lookup(iata: string | null | undefined): AirportEntry | null {
  if (!iata) return null;
  const code = iata.trim().toUpperCase();
  if (!IATA_AIRPORT.test(code)) return null;
  return AIRPORTS[code] ?? null;
}

/**
 * Resolve a 3-letter IATA airport code to its IANA timezone identifier
 * (e.g. "SGN" → "Asia/Saigon"). Returns `null` when the input isn't
 * IATA-shaped, isn't in the table, or is empty. Case-insensitive.
 *
 * Callers should default to "no special timezone treatment" on null —
 * that is, fall through to the runtime's local timezone. Asserting
 * a timezone we don't have would be worse than displaying in the
 * server's TZ.
 */
export function getAirportTimezone(iata: string | null | undefined): string | null {
  return lookup(iata)?.tz ?? null;
}

/**
 * Resolve a 3-letter IATA airport code to its ISO 3166-1 alpha-2
 * country code (e.g. "SGN" → "VN"). Returns `null` when the input
 * isn't IATA-shaped, isn't in the table, or the airport's country
 * couldn't be mapped to ISO. Case-insensitive.
 *
 * Used by the segment form to auto-fill origin / destination country
 * from a typed IATA. Callers should treat null as "don't know" — no
 * inference, no fallback country.
 */
export function getAirportCountry(iata: string | null | undefined): string | null {
  return lookup(iata)?.country ?? null;
}

/**
 * Resolve a 3-letter IATA airport code to WGS84 coordinates
 * (e.g. "SGN" → `{ lat: 10.819, lng: 106.652 }`). Returns `null`
 * when the input isn't IATA-shaped, isn't in the table, or the
 * airport row had no usable coords in the snapshot.
 *
 * Used by the trip-detail map to pin flight-destination airports.
 * Callers should treat null as "no pin" — silently omit rather than
 * mispinning to a fallback like (0, 0).
 */
export function getAirportCoords(
  iata: string | null | undefined,
): { lat: number; lng: number } | null {
  const entry = lookup(iata);
  if (!entry || entry.lat === undefined || entry.lng === undefined) return null;
  return { lat: entry.lat, lng: entry.lng };
}
