// Static IATA → airline-name lookup.
//
// The source-of-truth data is `iata-airlines.json` in this directory,
// generated by `scripts/fetch-airlines.ts` from OpenFlights. Airlines
// don't change often, so we ship the snapshot rather than calling out
// to an API at runtime.
//
// Two helpers:
//   getAirlineName(iata) — strict lookup; returns the resolved name or null.
//   displayCarrier(stored) — UI helper. If the stored value looks like
//     an IATA airline designator (2 chars, ≥1 letter, alphanumeric) and
//     we know it, return the airline name; otherwise pass the input
//     through unchanged. This lets the segment's data.carrier field
//     hold either a name ("Vietnam Airlines") or a code ("VN") and
//     render the friendly form either way without a data migration.

import airlinesData from './iata-airlines.json';

const AIRLINES: Readonly<Record<string, string>> = airlinesData as Record<string, string>;

// Two characters, alphanumeric, at least one letter. Matches the
// generator's accept rule in scripts/fetch-airlines.ts.
const IATA_DESIGNATOR = /^(?=.*[A-Z])[A-Z0-9]{2}$/;

// Reverse map: lowercased airline name → set of IATA codes that resolve
// to it. Lazily built on first use (dedup is the only current caller).
// Lowercased keys so "British Airways" and "british airways" match.
let nameToIatasCache: Map<string, Set<string>> | null = null;
function nameToIatas(): Map<string, Set<string>> {
  if (nameToIatasCache) return nameToIatasCache;
  const map = new Map<string, Set<string>>();
  for (const [iata, name] of Object.entries(AIRLINES)) {
    const key = name.toLowerCase();
    const set = map.get(key) ?? new Set<string>();
    set.add(iata);
    map.set(key, set);
  }
  nameToIatasCache = map;
  return map;
}

/**
 * Resolve a 2-character IATA airline designator to its registered name.
 * Returns `null` when the input isn't IATA-shaped, isn't in the table,
 * or is empty. Lookup is case-insensitive on the input.
 */
export function getAirlineName(iata: string | null | undefined): string | null {
  if (!iata) return null;
  const code = iata.trim().toUpperCase();
  if (!IATA_DESIGNATOR.test(code)) return null;
  return AIRLINES[code] ?? null;
}

/**
 * Render-time helper for a stored `data.carrier` value. The field
 * accepts free text, so any of these shapes can land in storage:
 *
 *   "Vietnam Airlines"   — already a name, pass through
 *   "VN"                 — IATA code we know → "Vietnam Airlines"
 *   "ZZ"                 — IATA-shaped but not in the table → "ZZ"
 *   "Some Custom Name"   — anything else → pass through
 *   "" / null / undefined → null
 */
export function displayCarrier(stored: string | null | undefined): string | null {
  if (stored === null || stored === undefined) return null;
  const trimmed = stored.trim();
  if (trimmed.length === 0) return null;
  const resolved = getAirlineName(trimmed);
  return resolved ?? trimmed;
}

/**
 * Render-time helper: combine a stored carrier + stored flightNumber
 * into the canonical "IATA NNN" form (e.g. "WY 287") that boarding
 * passes print. The stored carrier may be a name ("Oman Air") or an
 * IATA code ("WY"); the stored number is typically the bare digits
 * the extractor pulled off the document, but a user-edited row may
 * carry the full prefix inline. Either way the output normalises to
 * "IATA<space>NNN" when both halves are knowable, and falls back to
 * the raw number when no carrier IATA can be derived.
 *
 *   carrier="WY",          flightNumber="287"   → "WY 287"
 *   carrier="Oman Air",    flightNumber="287"   → "WY 287"  (name reverse-lookup)
 *   carrier=any,           flightNumber="WY287" → "WY 287"  (split + space)
 *   carrier=any,           flightNumber="WY 287"→ "WY 287"  (passthrough)
 *   carrier=null,          flightNumber="287"   → "287"     (nothing to prepend)
 *   carrier="Unknown Co",  flightNumber="287"   → "287"     (no IATA available)
 *   carrier=any,           flightNumber=null    → null
 */
export function formatFlightNumber(
  carrier: string | null | undefined,
  flightNumber: string | null | undefined,
): string | null {
  const raw = flightNumber?.trim();
  if (!raw) return null;

  // An inline prefix on the stored flight number wins over the
  // separate carrier field — if the user typed "WY 287" we honour
  // that even when carrier is blank. The lookahead pins the ≥1
  // letter rule to the first two chars (the IATA designator)
  // specifically, so "287F" doesn't get mis-split as carrier "28"
  // / number "7F" and "11 287" doesn't get treated as a carrier.
  const inline = /^(?=[A-Za-z0-9]?[A-Za-z])([A-Za-z0-9]{2})[\s-]*([0-9]{1,4}[A-Za-z]?)$/.exec(raw);
  if (inline) {
    return `${inline[1]!.toUpperCase()} ${inline[2]!.toUpperCase()}`;
  }

  // Bare number → derive the IATA from the carrier field. The carrier
  // may be the IATA itself ("WY") or the resolved name ("Oman Air");
  // both reverse cleanly to the 2-letter code we want to prepend.
  const iata = carrierToIata(carrier);
  if (iata && /^[0-9]{1,4}[A-Za-z]?$/.test(raw)) {
    return `${iata} ${raw.toUpperCase()}`;
  }

  return raw;
}

function carrierToIata(stored: string | null | undefined): string | null {
  if (!stored) return null;
  const trimmed = stored.trim();
  if (!trimmed) return null;
  // Already an IATA code we know — keep it.
  if (getAirlineName(trimmed)) return trimmed.toUpperCase();
  // A name we can reverse-resolve. Multi-match airlines (rare) pick
  // the first sorted code — for display this is fine; we surface
  // *a* legitimate code, not every alias.
  return getIatasForName(trimmed)[0] ?? null;
}

/**
 * Resolve a name back to its IATA designator(s). Returns an empty array
 * for unknown names or non-string input. Multiple codes are possible
 * when an airline appears under more than one designator (regional
 * subsidiaries, code reuse) — rare, but we surface them all so callers
 * doing equality lookups don't silently miss a row.
 *
 * Used by `equivalentCarrierForms` below. Most feature code wants that
 * higher-level helper, not this one.
 */
export function getIatasForName(name: string | null | undefined): readonly string[] {
  if (!name) return [];
  const key = name.trim().toLowerCase();
  if (key.length === 0) return [];
  const set = nameToIatas().get(key);
  return set ? [...set].sort() : [];
}

/**
 * Equivalent storage forms for a stored carrier value — used by dedup
 * (or any other equality lookup) so a query for "British Airways"
 * matches segments stored as "BA" and vice versa. The input itself is
 * always in the result so callers don't need a separate branch when
 * the value is unrecognised.
 *
 * Examples:
 *   "British Airways" → ["BA", "British Airways"]
 *   "BA"              → ["BA", "British Airways"]
 *   "Some Custom Co"  → ["Some Custom Co"]   (passthrough)
 *   ""/null           → []
 *
 * Order is not guaranteed; callers should use set-membership semantics.
 */
export function equivalentCarrierForms(carrier: string | null | undefined): string[] {
  if (!carrier) return [];
  const trimmed = carrier.trim();
  if (trimmed.length === 0) return [];

  const equivalents = new Set<string>([trimmed]);
  const resolvedName = getAirlineName(trimmed);
  if (resolvedName) {
    // Input was an IATA code → add its name and any sibling codes.
    equivalents.add(resolvedName);
    for (const code of getIatasForName(resolvedName)) equivalents.add(code);
  } else {
    // Input was a name (or unknown) → add any IATA codes that resolve
    // to that name. For an unknown name, this is a no-op.
    for (const code of getIatasForName(trimmed)) equivalents.add(code);
  }
  return [...equivalents];
}
